#
# appveyor.yml
#
#

version: 0.0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2015

build_script:
  - choco install opencover.portable
  - choco install codecov
  - dotnet build

test_script:
  - OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test Api.Tests" -output:".\coverage.xml" -oldStyle
  - codecov -f "coverage.xml"

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/12f141b3bafb5e61f9ad
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
